CREATE TABLE ROOM(
  ROOM_ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME            VARCHAR(16)   NOT NULL,
  ROOM_NUMBER     CHAR(2)       NOT NULL UNIQUE,
  BED_INFO        CHAR(2)       NOT NULL,
  PRICE_PER_NIGHT DECIMAL(10,2) NOT NULL DEFAULT 99.00,
  MAX_CAPACITY    INT           NOT NULL DEFAULT 2
);

CREATE TABLE GUEST(
  GUEST_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME    VARCHAR(64),
  LAST_NAME     VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS       VARCHAR(64),
  COUNTRY       VARCHAR(32),
  STATE         VARCHAR(12),
  PHONE_NUMBER  VARCHAR(24)
);

CREATE TABLE RESERVATION(
  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID        BIGINT        NOT NULL,
  GUEST_ID       BIGINT        NOT NULL,
  CHECK_IN_DATE  DATE          NOT NULL,
  CHECK_OUT_DATE DATE          NOT NULL,
  STATUS         VARCHAR(16)   NOT NULL DEFAULT 'PENDING',
  TOTAL_PRICE    DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  CONSTRAINT CHK_RES_DATE_RANGE CHECK (CHECK_OUT_DATE > CHECK_IN_DATE),
  CONSTRAINT CHK_RES_STATUS CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'CANCELLED'))
);

ALTER TABLE RESERVATION ADD FOREIGN KEY (ROOM_ID)  REFERENCES ROOM(ROOM_ID);
ALTER TABLE RESERVATION ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST(GUEST_ID);
CREATE INDEX IDX_RES_CHECKIN  ON RESERVATION(CHECK_IN_DATE);
CREATE INDEX IDX_RES_CHECKOUT ON RESERVATION(CHECK_OUT_DATE);
CREATE INDEX IDX_RES_GUEST_ID ON RESERVATION(GUEST_ID);
CREATE INDEX IDX_RES_ROOM_ID  ON RESERVATION(ROOM_ID);
CREATE INDEX IDX_RES_STATUS   ON RESERVATION(STATUS);

CREATE TABLE RESERVATION_NIGHT(
  RESERVATION_NIGHT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RESERVATION_ID       BIGINT NOT NULL,
  ROOM_ID              BIGINT NOT NULL,
  STAY_DATE            DATE   NOT NULL,
  CONSTRAINT UK_RES_NIGHT_ROOM_DATE UNIQUE (ROOM_ID, STAY_DATE)
);

ALTER TABLE RESERVATION_NIGHT ADD FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION(RESERVATION_ID);
ALTER TABLE RESERVATION_NIGHT ADD FOREIGN KEY (ROOM_ID)        REFERENCES ROOM(ROOM_ID);
CREATE INDEX IDX_RES_NIGHT_RESERVATION_ID ON RESERVATION_NIGHT(RESERVATION_ID);
CREATE INDEX IDX_RES_NIGHT_ROOM_ID        ON RESERVATION_NIGHT(ROOM_ID);
CREATE INDEX IDX_RES_NIGHT_STAY_DATE      ON RESERVATION_NIGHT(STAY_DATE);
